name: Auto Flakey Test
title: '[Flake]: '
description: Automated flakey test tracker
labels: ['Flake']
body:
  - type: input
    id: flake_count
    attributes:
      label: Flake Count
      description: How many times has flake occured?
    validations:
      required: true
  - type: textarea
    id: occurrences
    attributes:
      label: Distinct occurrences of this flake
    validations:
      required: true